# options:
#    auto-update - Github 新版本自動檢查更新
#    armor-update-interval - 黏液科技裝備效果更新週期
#    enable-armor-effects - 裝備效果的開關
#    chat-prefix - 黏液科技所有訊息的前綴
#    auto-save-delay-in-minutes - 自動儲存資料的週期，單位為分鐘
#    legacy-ore-washer - 是否使用舊版的礦物洗滌機機制
#    legacy-dust-washer - 是否使用舊版的礦物洗滌機機制
#    legacy-ore-grinder - 是否使用旧版的碎矿机机制 是否使用舊版的粉碎機機制
#    language - 黏液科技的文字語言（不包含物品）
#    enable-translations - 是否啟用多語言功能設定
#    backwards-compatibility - 物品向後相容模式，關閉後物品會使用新版物品系統
#                             將提升伺服器效能
#    log-duplicate-block-entries - 是否輸出發現重複方塊的警告
#    burn-players-when-radioactive - 是否在當玩家暴露於輻射中燃燒玩家
#    drop-excess-sf-give-items - 當使用指令給予 Slimefun 物品時，在背包已滿狀態下直接掉落物品
#    backup-data - 自動備份資料
options:
  auto-update: true
  backwards-compatibility: false
  chat-prefix: '&a&lSlimefun 4 &7> '
  armor-update-interval: 10
  enable-armor-effects: true
  auto-save-delay-in-minutes: 10
  legacy-ore-washer: false
  legacy-dust-washer: false
  legacy-ore-grinder: true
  language: zh-TW
  enable-translations: true
  log-duplicate-block-entries: true
  burn-players-when-radioactive: true
  drop-excess-sf-give-items: false
  backup-data: true

guide:
  # 是否在指南中顯示原版物品合成配方
  show-vanilla-recipes: true
  # 是否在玩家第一次加入伺服器時自動贈送黏液科技指南
  receive-on-first-join: true
  # 是否在搜尋中顯示隱藏物品
  show-hidden-item-groups-in-search: false

researches:
  # 是否允许创造模式玩家免费解锁研究
  free-in-creative-mode: true
  # 是否在解鎖研究時發射煙火
  enable-fireworks: true
  # 是否使用遊戲幣替換使用經驗值解鎖
  use-money-unlock: false
  # 經驗自動轉換到遊戲幣的倍率
  currency-cost-convert-rate: 25.0
  # 是否停用解鎖研究時的動畫
  disable-learning-animation: false

URID:
  info-delay: 3000
  custom-ticker-delay: 10
  enable-tickers: true

networks:
  max-size: 200
  cargo-ticker-delay: 0
  enable-visualizer: true
  delete-excess-items: false

talismans:
  use-actionbar: true

metrics:
  auto-update: false

backpack:
  # 背包擁有者離線時是否允許背包被打開
  allow-open-when-owner-offline: true

research-ranks:
  - 弱小如雞
  - 初生之犢
  - 蜘途小蛛
  - 村民出身
  - 初出茅廬
  - 笨拙的學徒初學者
  - 璞玉未成的初學者
  - 大器晚成的初學者
  - 普普通通的初學者
  - 璞玉未成的學徒
  - 普普通通的學徒
  - 技巧熟練的學徒
  - 大放異彩的法師
  - 煉鐵成鋼的法師
  - 年輕有為的魔導士
  - 大器晚成的魔導士
  - 千篇一律的魔導士
  - 普普通通的魔導士
  - 精練成熟的魔導士
  - 技巧熟練的魔導士
  - 千錘百鍊的魔導士
  - 舉世聞名的魔導士
  - 大器晚成的巫師
  - 普普通通的巫師
  - 璞玉未成的巫師
  - 技巧熟練的巫師
  - 舉世聞名的巫師
  - 百年一見的巫師
  - 年輕有為的大師
  - 大器晚成的大師
  - 大放異彩的大師
  - 名符其實的大師
  - 聲名大噪的大師
  - 技巧熟練的大師
  - 煉鐵成鋼的大師
  - 舉世聞名的大師
  - 精練成熟的大師
  - 天選者
